security:
  enable_authenticator_manager: true
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    main:
      lazy: true
      provider: app_user_provider
      entry_point: App\Security\LoginFormAuthenticator
      custom_authenticators:
        - App\Security\GoogleAuthenticator
        - App\Security\LoginFormAuthenticator

      logout:
        path: app_logout
        target: app_login

      remember_me:
        secret: "%kernel.secret%"
        lifetime: 604800
        path: /
        always_remember_me: true

  access_control:
    - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
